/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __ark_Odometry_hpp__
#define __ark_Odometry_hpp__

#include <string>
#include "ark/Header.hpp"
#include "ark/PoseWithCovariance.hpp"
#include "ark/TwistWithCovariance.hpp"

namespace ark
{

class Odometry
{
    public:
        ark::Header header;

        std::string child_frame_id;

        ark::PoseWithCovariance pose;

        ark::TwistWithCovariance twist;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "Odometry"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int Odometry::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Odometry::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int Odometry::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t Odometry::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* Odometry::getTypeName()
{
    return "Odometry";
}

int Odometry::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->header._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    char* child_frame_id_cstr = (char*) this->child_frame_id.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &child_frame_id_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->pose._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->twist._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Odometry::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->header._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __child_frame_id_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__child_frame_id_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__child_frame_id_len__ > maxlen - pos) return -1;
    this->child_frame_id.assign(((const char*)buf) + offset + pos, __child_frame_id_len__ - 1);
    pos += __child_frame_id_len__;

    tlen = this->pose._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->twist._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Odometry::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->header._getEncodedSizeNoHash();
    enc_size += this->child_frame_id.size() + 4 + 1;
    enc_size += this->pose._getEncodedSizeNoHash();
    enc_size += this->twist._getEncodedSizeNoHash();
    return enc_size;
}

uint64_t Odometry::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == Odometry::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)Odometry::getHash };

    uint64_t hash = 0x97f82279756d9d18LL +
         ark::Header::_computeHash(&cp) +
         ark::PoseWithCovariance::_computeHash(&cp) +
         ark::TwistWithCovariance::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
